### PR TITLE
Add Blockchair API into GraphQL

### PR DESCRIPTION
**Pull request by dnaiel0809**
- Add the Blockchair API and its schema which hosted on the [repo](https://github.com/neu-info7500-spring-04/Blockchair-API-Schema)

### CODE REVIEW

**Review by erinmhpark — DISMISSED** [review]
* Works well with bitcoin-explorer repo
* No bugs in the code

**Comment by Danielnewheart** [comment]
I think you shouldn't delete .env.example but I'll add it back.

**Review by Danielnewheart — CHANGES_REQUESTED** [review]
@dnaiel0809  You have to retore .env.example file or I cannot approve your pr, which affect other students making pr on bitcoin-explorer repo.

**Comment by dnaiel0809** [comment]
@Danielnewheart Sorry for deleting the .env.example, I add this file back. Could you check my pr? Thanks!

**Review by Danielnewheart — DISMISSED** [review]

**Comment by Danielnewheart** [comment]
You fine. No worry. @dnaiel0809  You just need to resolve the conflicts and merge it ASAP to make sure we can run well on the explorer repo's main branch.

**Comment by dnaiel0809** [comment]
Conflicts were solved. Please review and approve it. Thanks.

**Review by Danielnewheart — APPROVED** [review]

**Pull request merged**
